AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: |
  Static Assets Deployment. A custom CloudFormation resource that deploys static
  web assets to an S3 bucket.
Parameters:
  StaticAssetsLayerArn:
    Type: String
    Description: ARN of the layer containing the static assets to deploy.
  StaticAssetsBucket:
    Type: String
    Description: The bucket to deploy the static assets to.
  CacheControl:
    Type: String
    Description: The Cache-Control meta-data to add to s3 asset uploads
    Default: "max-age=31536000, immutable"
  Timeout:
    Type: Number
    Description: The timeout for deployment of the static assets.
    Default: "10"
Metadata:
  AWS::ServerlessRepo::Application:
    Name: static-assets-deployment
    Description: A custom CloudFormation resource to deploy static assets to an S3 bucket
    Author: Andy Caine
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['cloudformation', 's3', 'python']
    HomePageUrl: https://github.com/andycaine/static-assets-deployment#readme
    SemanticVersion: 0.2.0
    SourceCodeUrl: https://github.com/andycaine/static-assets-deployment
Resources:

  StaticAssetsDeployer:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      Runtime: python3.12
      Handler: app.handler
      CodeUri: ./sad
      Timeout: !Ref Timeout
      Environment:
        CACHE_CONTROL: !Ref CacheControl
      Layers:
        - !Ref StaticAssetsLayerArn
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StaticAssetsBucket

  StaticAssetsDeployment:
    Type: Custom::StaticAssetsDeployment
    Properties:
      ServiceToken: !GetAtt StaticAssetsDeployer.Arn
      BucketName: !Ref StaticAssetsBucket
